module Editorial
  # Maps the free-text seed categories used by imported words onto the six
  # delivery categories — a copy of `DeliveredWord._seedCategoryFallback` in
  # lib/features/content_sync/domain/delivery_models.dart, so the Studio form
  # shows the same category the app uses.
  module SeedCategories
    MAP = {
      "family" => "chhungkua",
      "home" => "chhungkua",
      "household" => "chhungkua",
      "people" => "chhungkua",
      "community" => "chhungkua",
      "school" => "sikul",
      "learning" => "sikul",
      "grammar-term" => "sikul",
      "grammar-time" => "sikul",
      "animals" => "nungcha",
      "nature-wildlife" => "nungcha",
      "culture-animal" => "nungcha",
      "nature" => "khawvel",
      "plants" => "khawvel",
      "nature-plant" => "khawvel",
      "nature-food" => "khawvel",
      "geography" => "khawvel",
      "seasons" => "khawvel",
      "calendar" => "khawvel",
      "time" => "khawvel",
      "colors" => "khawvel",
      "body" => "khawvel",
      "health" => "khawvel",
      "numbers" => "khawvel",
      "objects" => "khawvel",
      "culture" => "nunphung",
      "culture-instrument" => "nunphung",
      "culture/folklore" => "nunphung",
      "legend" => "nunphung",
      "traditional_dress" => "nunphung",
      "culture-folklore" => "nunphung",
      "culture-tradition" => "nunphung",
      "culture-object" => "nunphung",
      "culture-literature" => "nunphung",
      "culture-sport" => "nunphung",
      "folktale/legend" => "nunphung",
      "festival/culture" => "nunphung",
      "festivals" => "nunphung",
      "crafts" => "nunphung",
      "history" => "nunphung",
      "values" => "nunphung",
      "abstract/values" => "nunphung",
      "abstract-value" => "nunphung",
      "idiom" => "nunphung",
      "manners" => "nunphung",
      "greetings" => "nunphung",
      "clothing" => "nunphung",
      "clothing/traditional" => "nunphung",
      "daily-life" => "nunphung",
      "daily_life" => "nunphung",
      "occupations" => "nunphung",
      "feelings" => "nunphung",
      "emotions" => "nunphung",
      "abstract" => "nunphung",
      "abstract-noun" => "nunphung",
      "abstract-action" => "nunphung",
      "abstract-emotion" => "nunphung",
      "abstract-quality" => "nunphung",
      "qualities" => "nunphung",
      "adjectives" => "nunphung",
      "adjective-size" => "nunphung",
      "adjective-quality" => "nunphung",
      "adjective-distance" => "nunphung",
      "adjective-temperature" => "nunphung",
      "adjective-quantity" => "nunphung",
      "adjective-color" => "nunphung",
      "adjective-number" => "nunphung",
      "transport" => "nunphung",
      "sport" => "nunphung",
      "sport-action" => "nunphung",
      "verbs" => "thiltih",
      "actions" => "thiltih",
      "adverbs" => "thiltih",
      "body parts" => "khawvel",
      "body_parts" => "khawvel",
      "body/food" => "khawvel",
      "food" => "khawvel",
      "food/body" => "khawvel",
      "food/nature" => "khawvel",
      "directions" => "khawvel",
      "places" => "khawvel",
      "sounds" => "khawvel",
      "nature/objects" => "khawvel",
      "tools" => "nunphung",
      "tools/nature" => "nunphung",
      "traditional_culture" => "nunphung",
      "vehicles" => "nunphung",
      "verbs/craft" => "nunphung",
      "people/abstract" => "nunphung"
    }.freeze

    def self.for(seeds)
      Array(seeds).each { |seed| return MAP[seed.to_s] if MAP.key?(seed.to_s) }
      nil
    end
  end
end
